### ISSUE TITLE
Unhandled sensor type leafwetness

### ISSUE THREAD

**Issue by Anto79-ops** [garbled1/homeassistant_ecowitt#102]
Hi, seems leafwetness sensor and battery is not supported yet

for example: ch1 value 89

89 is 89%

thanks 

`Logger: custom_components.ecowitt
Source: custom_components/ecowitt/__init__.py:274
Integration: Ecowitt Weather Station
First occurred: March 17, 2022, 12:43:39 PM (8170 occurrences)
Last logged: 9:57:22 AM

Unhandled sensor type leafwetness_ch1 value 89, file a PR.
Unhandled sensor type leafwetness_ch1 value 92, file a PR.
Unhandled sensor type leafwetness_ch1 value 93, file a PR.
Unhandled sensor type leaf_batt1 value 1.72, file a PR.
Unhandled sensor type leafwetness_ch1 value 91, file a PR.`

**Comment by RJ-Make** [comment]
Would also love to see the leaf wetness (WN35BN) sensor added.

**Comment by RJ-Make** [comment]
This Leaf Sensor makes a FANTASTIC rain detector. I've been doing some testing with it and placing the sensor on an angle helps with 'drain off' after a rain.

This morning it started 'misting' out, and as you can see the leaf sensor picked up very fast as compared to the rain gauge. 

![2022-04-07 07_11_31-Window](https://user-images.githubusercontent.com/8496835/162186804-c3bc3752-f363-498c-87f8-e59a93b3dde7.png)

![2022-04-07 07_12_25-Window](https://user-images.githubusercontent.com/8496835/162186900-2f4cf301-99ef-4178-8fa8-eb32e494ca76.png)

**Comment by RJ-Make** [comment]
Would any of you fantastic contributors consider adding this sensor? If you need a sensor, I would be willing to ship you one (US or CA)
