### ISSUE TITLE
Unhandled Sensor Type - WN34L Water Temp Sensor

### ISSUE THREAD

**Issue by nickqp** [garbled1/homeassistant_ecowitt#104]
I'm getting the following error for the water temperature sensor and its not showing up as an entity. The GW1100 sensors are working fine:

Logger: custom_components.ecowitt
Source: custom_components/ecowitt/__init__.py:269
Integration: Ecowitt Weather Station

Unhandled sensor type tf_ch1 value 79.0, file a PR.
Unhandled sensor type tf_batt1 value 1.54, file a PR.
Unhandled sensor type tf_ch1 value 78.8, file a PR.
Unhandled sensor type tf_ch1 value 78.4, file a PR.
Unhandled sensor type tf_ch1 value 78.6, file a PR.

Any help is appreciated. Thanks!

**Comment by snarlingllama** [comment]
Having the same issue. Logs produce the same error messages that nickqp posted. Thank you in advance for your help!

**Comment by snarlingllama** [comment]
Happy to report that version 0.7 resolved this issue for me.

**Comment by nickqp** [comment]
Resolved for me as well. Thanks.
