### ISSUE TITLE
Ecowitt appears in HACS only

### ISSUE THREAD

**Issue by timothybuchanan** [garbled1/homeassistant_ecowitt#121]
i used HACS to add ecowitt and a new folder appeared in custom_components. Instructions then say to go to the other integrations and add ecowitt. But I can't. it doesn't appear in the list of integrations to add. What now?

**Comment by RJ-Make** [comment]
I'm not sure I understand..., Once you have installed Ecowitt via HACS, you need to restart HA and then add the integration in HA via Devices and Services.

**Comment by imthebojo** [comment]
Im the same. Installed via HACS and cannot see it as an available addon via Settings > Devices and Services > " + Add Integration"
I have restarted HA via terminal "ha hassio restart"
I have updated to HA 8.1 (i was ancient)
The files exist under: "\\IPADDRESS\config\custom_components\ecowitt\.."     (SAMBA)

**Comment by timothybuchanan** [comment]
I restarted HA several times and even rebooted the pi, but ecowitt only showed up the next day in integrations. Go figure.

**Comment by slarrain** [comment]
I'm having the same problem. Still not showing up. I'll wait until tomorrow.

**Comment by imthebojo** [comment]
Yes, it was a wait until tomorrow that solved the issue

**Comment by slarrain** [comment]
It did show up on the next day.

**Comment by DoerakkerHA** [comment]
As with most addons: you have to enable the devices after creation or wait for a reboot to enable the entities



Kind Regards
ROnald Groeneveld


Sent from my iPhone 
+31 650 989 689
