### ISSUE TITLE
Core integration

### ISSUE THREAD

**Issue by pvizeli** [garbled1/homeassistant_ecowitt#129]
Hi @garbled1 

I would like to make a core integration with this. Can I use your code base to start with and in terms of the Home Assistant CLA?
Can I get also maintenance access to the library or can we move that to home-assistant-libs?

Pascal

**Comment by sam-ward** [comment]
I'm not sure where @garbled1 is at the moment, but he had already made a start on refactoring the integration and getting it pulled into core,  but it stalled awaiting review by the HA dev team  https://github.com/home-assistant/core/pull/60541

**Comment by garbled1** [comment]
I've been pretty busy lately, and sadly haven't had time to keep things moving in HA.

I really do want this integrated, as my ability to keep maintaining it is low.  If 1-2 people were interested in helping the maintenance of this, and the library, I'd be willing to give access.

**Comment by DoerakkerHA** [comment]
Hi Tim,

i have read your message and I’d like to help out. 

Tell me what you want done and I’ll see what I can do or learn to do ;-) 




Kind Regards
ROnald Groeneveld


Sent from my iPhone 
+31 650 989 689

**Comment by drsmarsden** [comment]
I am happy to help - I am actually running 2 instances in HA with 2 GW1100As

**Comment by pvizeli** [comment]
I created a new library: https://github.com/home-assistant-libs/aioecowitt and my custom component are also soon ready. The issue with this custom component is, it have wrong asyncio handling + some things that never get pass on core. The new library simplify the handling - the core integration don't need to be that complex

**Comment by adorobis** [comment]
Great to see this now in Core. Is the overall scope the same as the HACS integration? What would be the main differences? I think we can have only one custom data target in the station so can't use both at the same time.

**Comment by sam-ward** [comment]
I don't know much about it, I just noticed it getting merged.  It was pvizeli who contributed it.  I *think* originally it started from a v2 that garbled was working on,  but I also get the impressions its been very heavily refactored and reworked from that.

**Comment by pvizeli** [comment]
It's a mix between pyecowitt and ecowitt2mqtt. Properly I will add more calculations over from ecowitt2mqtt or hopefully someone will help at aioecowitt library. We will see
