### ISSUE TITLE
WH51 entity not showing

### ISSUE THREAD

**Issue by cdouet** [garbled1/homeassistant_ecowitt#13]
Hello,

I got the ecowitt integration for homeassistant running for my gw1000 gateway. I can see the indoor temperature, indoor humidity, absolute pressure and relative pressure entities. However, i cant see the WH51 sensor entity (which I can see on my WS view app). Is there any specific configuration to be done?

Thanks in advance,

Charles

**Comment by garbled1** [comment]
Are you running the master version of the ecowitt component from HACS?

**Comment by cdouet** [comment]
Hello,

Somehow, my 2 sets of WH51 sensors showed up yesterday after I did a couple of updates...
Thanks!

Charles
