### ISSUE TITLE
WN1910CA no Data to HAS

### ISSUE THREAD

**Issue by DaHype** [garbled1/homeassistant_ecowitt#136]
I have the Gateway  GW1100 and as Display also the WN1910CA. Gateway 1100 Display fine in my HAS as entity in the Integration. But Data from WN1910CA Not. Of course i have Set the Same Settings as the Gateway.  No Display ;-(

**Comment by DoerakkerHA** [comment]
Could you be a little more specific ? 

Any relevant log data for example or more info in general? 



Kind Regards
ROnald Groeneveld


Sent from my iPhone 
+31 650 989 689

**Comment by DaHype** [comment]
Log Data dont exist because No Data from the Display Receive in the HAS Integration. The Device is OK. The Settings also, Display Wn1910 is online...

Same Settings in Dashboard as the GW.
Means Port 4199. homeassistant.local

So only GW1100 shown but No entities from WN1910CA

**Comment by DaHype** [comment]
![Screenshot_20220906-213120_Home Assistant](https://user-images.githubusercontent.com/102579433/188722741-17882cc3-176f-442f-862c-74c5c89fa4f5.jpg)
