### ISSUE TITLE
Ecowitt not loading

### ISSUE THREAD

**Issue by paulonHA** [garbled1/homeassistant_ecowitt#137]
Hi, I just installed the integration and I get the following message in the logs:

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:172
First occurred: 16:33:21 (2 occurrences)
Last logged: 16:33:21

Error unloading entry Ecowitt on port 4199 for sensor
Error unloading entry Ecowitt on port 4199 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 496, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 246, in async_unload_entry
    return await component.async_unload_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 172, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

What can I do to fix this?

**Comment by sam-ward** [comment]
Home assistant now includes an official ecowitt integration with 2022.9 https://www.home-assistant.io/integrations/ecowitt/  I would suggest removing this one and going with the official one.

**Comment by paulonHA** [comment]
Thanks for your message. I actually was able to fix the problem 2 days ago and I forgot to close the issue here. The Problem was related to the host name/IP
