### ISSUE TITLE
Question about Battery Values

### ISSUE THREAD

**Issue by isuee94** [garbled1/homeassistant_ecowitt#15]
First of all, thanks for creating this!  I'm just getting into Home Assistant, but this adds another piece to the puzzle for moving everything into a single pane of glass.

In terms of the reported battery levels from the various sensors, what are the units on the value?  I'm getting 1.6 from a couple of my sensors and 0 from a couple of others.

**Comment by garbled1** [comment]
I'll be honest, I have no idea.  None of my sensors report battery values, so I really don't know what the range is. I guess it would be helpful to put various batteries of known-state in one and tell me what it says so I could at least document it?  My display seems to show different things for the battery values, it just doesn't present them via the API.

My theory from seeing a few bug reports of things is that 0 is "ok", but it's not clear to me...thats just a wild guess?

**Comment by Bart39** [comment]
I believe all fine offset/ aws/ Ecowitt clones battery values only report one of 2 values: “0” = good, “1” = low

**Comment by garbled1** [comment]
I've noticed a few unhandled sensor PR's here have battery values of stuff like "5".  No idea what that is.. I should get one of those gx1000's and see if it spits battery values for me.

**Comment by garbled1** [comment]
I have rewritten the handling of all known battery sensors in 0.5.  They should be more or less sane now.
