### ISSUE TITLE
Unhandled sensor type wh25batt and maxdailygustms

### ISSUE THREAD

**Issue by jdvldr** [garbled1/homeassistant_ecowitt#17]
2020-08-13 06:29:39 WARNING (MainThread) [custom_components.ecowitt] Unhandled sensor type wh25batt value 0, file a PR.
2020-08-13 06:29:39 WARNING (MainThread) [custom_components.ecowitt] Unhandled sensor type maxdailygustms value 1.0, file a PR.

**Comment by moravszky** [comment]
Same here:
WARNING (MainThread) [custom_components.ecowitt] Unhandled sensor type maxdailygustms value 2.59, file a PR.

**Comment by moravszky** [comment]
I do not know Python, but just looking at the code:
The line in the log must come from this code:

    async def _async_ecowitt_update_cb(weather_data):
        """Primary update callback called from pyecowitt."""
        _LOGGER.debug("Primary update callback triggered.")
        if not hass.data[DOMAIN][DATA_READY]:
            await _first_data_rec(weather_data)
            return
        for sensor in weather_data.keys():
            if sensor not in SENSOR_TYPES:
                if sensor not in IGNORED_SENSORS:
                    _LOGGER.warning("Unhandled sensor type %s value %s, " +
                                    "file a PR.", sensor, weather_data[sensor])
        async_dispatcher_send(hass, DOMAIN)

But maxdailygustms is listed in IGNORED_SENSORS, so why is the _LOGGER command called?

IGNORED_SENSORS = [
    'tempinf',
    'tempf',
    'temp1f',
    'temp2f',
    'temp3f',
    'temp4f',
    'temp5f',
    'temp6f',
    'temp7f',
    'temp8f',
    'dateutc',
    'windgustms',
    'windspeedms',
    'windspdms_avg10m'
    'maxdailygustms',
    'windchillf',
    'dewpointf',
    'dewpointinf',
    'dewpoint1f',
    'dewpoint2f',
    'dewpoint3f',
    'dewpoint4f',
    'dewpoint5f',
    'dewpoint6f',
    'dewpoint7f',
    'dewpoint8f',
    DATA_PASSKEY,
    DATA_STATIONTYPE,
    DATA_FREQ,
    DATA_MODEL,
]

**Comment by scooper1** [comment]
because  'windspdms_avg10m' has a missing comma



------ Original Message ------

**Comment by GSzabados** [comment]
@scooper1, you have pretty good eyes. I've looked at it yesterday just before midnight, but couldn't see that. Indeed I had fallen asleep meanwhile looking at the code and woke up dropping the phone.

I will add it another PR together the other battery value.

**Comment by garbled1** [comment]
Fixed with merge of PR#24
