### ISSUE TITLE
'Rate' should be 'Total' for all but one rain value ?

### ISSUE THREAD

**Issue by mr-sneezy** [garbled1/homeassistant_ecowitt#19]
Love the Ecowitt integration, I installed very easily via HACS.

Feedback.
I note that all my rain sensor values are appended with 'rate' in HA entities, when I think only the first one should be 'rain rate'.
Should the others not be appended with 'total', like Daily Rain Total or Weekly Rain Total ?
I can change this inside HA entities naming override but would be better to change in Ecowitt integration. 

For reference, here is all my sensors, with some names over-ridden, like the rain hourly, daily, weekly, etc entities to remove 'rate'.
![image](https://user-images.githubusercontent.com/6261419/90506453-76ee6b00-e193-11ea-9094-bcc9da4fa7b6.png)

**Comment by garbled1** [comment]
good catch
