### ISSUE TITLE
"Max Daily Wind Gust" and "Max Daily Wind Gust 2", what is the difference ?

### ISSUE THREAD

**Issue by mr-sneezy** [garbled1/homeassistant_ecowitt#20]
I've looked at three days of data from my HA 'history' for those two sensor values. I've noted that there is a constant ratio offset of 1:1.609 between them so far, which is coincidentally the multiplier to convert mph to kph. Just a coincidence ?
Can anyone else can verify that relationship over a few days worth of max wind data ?

**Comment by GSzabados** [comment]
@mr-sneezy, I checked as well, and found the same as you. The second is in kph, as I remember. I am looking for a way to change the unit to be kph for it.

**Comment by mr-sneezy** [comment]
I think the units are set in the init.py file (See Line 280 as an example). 
I don't know anything about Python, not sure if we can just edit our files on HA directly and expect it to use the update.

**Comment by cpuks** [comment]
Line 249-252:
    TYPE_MAXDAILYGUST: ("Max Daily Wind Gust", SPEED_MILES_PER_HOUR,
                        TYPE_SENSOR, None, "mdi:weather-windy", S_IMPERIAL),
    TYPE_MAXDAILYGUSTKMH: ("Max Daily Wind Gust", SPEED_MILES_PER_HOUR,
                           TYPE_SENSOR, None, "mdi:weather-windy", S_METRIC),

Looks like typo so just corrected to KILOMETERS:
    TYPE_MAXDAILYGUST: ("Max Daily Wind Gust", SPEED_MILES_PER_HOUR,
                        TYPE_SENSOR, None, "mdi:weather-windy", S_IMPERIAL),
    TYPE_MAXDAILYGUSTKMH: ("Max Daily Wind Gust", SPEED_**KILOMETERS**_PER_HOUR,
                           TYPE_SENSOR, None, "mdi:weather-windy", S_METRIC),

**Comment by GSzabados** [comment]
I've created a Pull request to get this solved.

**Comment by garbled1** [comment]
This was pulled.  Marking fix.
