### ISSUE TITLE
Is there a way to enable this as a weather entity?

### ISSUE THREAD

**Issue by pgregg88** [garbled1/homeassistant_ecowitt#21]
Hello. I'm trying to create a weather entity from my Ecowitt sensors that can be consumed by the custom weather card. I've searched for an answer, but I'm clearly missing a concept or something. Can anyone point me in the right direction? Thx.

**Comment by cpuks** [comment]
Try this one [](https://github.com/r-renato/ha-card-weather-conditions) works well for me

**Comment by garbled1** [comment]
I'm actually using the same one.  It's super good.
