### ISSUE TITLE
Unhandled sensors

### ISSUE THREAD

**Issue by tjaart-github** [garbled1/homeassistant_ecowitt#26]
Thank you for your hard work on this - all of us using your code really appreciate it.

Here are a few more errors for missing sensors. I have a GW1003 with additional lightning detector:
WARNING (MainThread)   [custom_components.ecowitt] Unhandled sensor type lightning value , file a   PR.
WARNING (MainThread)   [custom_components.ecowitt] Unhandled sensor type wh80batt value 2.38, file a   PR.
WARNING (MainThread)   [custom_components.ecowitt] Unhandled sensor type maxdailygustms value 2.0,   file a PR.
WARNING (MainThread)   [custom_components.ecowitt] Unhandled sensor type lightning_time value , file   a PR.
WARNING (MainThread)   [custom_components.ecowitt] Unhandled sensor type lightning_num value 0, file   a PR.
WARNING (MainThread)   [custom_components.ecowitt] Unhandled sensor type lightning value , file a   PR.

**Comment by garbled1** [comment]
These should be fixed in 0.4
