### ISSUE TITLE
Can't find the Options

### ISSUE THREAD

**Issue by sportbikearmy** [garbled1/homeassistant_ecowitt#31]
Hi,

Running Home Assistant 0.118.4 ecowitt 0.5 installed using HACS 1.6.2 on raspberry pi 3b.
Ecowitt GW1000 up and running and configured to send on port 4199.

I'm new to using HACS and can't find where the Options for ecowitt integration are entered.  Nothing seems to happen after ecowitt is installed and HA restarted other than it appears in the HACS integrations list and the followings appear in the Log:

2020-11-27 21:23:37 DEBUG (MainThread) [custom_components.hacs.repository.integration.garbled1.homeassistant_ecowitt] Getting repository information
2020-11-27 21:23:37 DEBUG (MainThread) [custom_components.hacs.repository.integration.garbled1.homeassistant_ecowitt] Running checks against 0.5

What am I missing?

**Comment by garbled1** [comment]
Go to integrations, hit the + and search for ecowitt, Click on it and it should give you instructions to fill in the port # and do the remainder of the setup.  Once it's setup, you can go back into integrations, find the ecowitt integration, and select options at the bottom of the card.

**Comment by sportbikearmy** [comment]
Thanks for that, I go it now.

The part I found confusing is that HACS also has an "Integrations" page so when the instructions say "Go to Integrations" I thought that meant in HACS.

To make it clearer for the next person who isn't sure how to install the component using HACS:

1. Go to HACS -> Integrations -> Click "+"
2. Search for "Ecowitt Weather Station" repository and add to HACS
3. Restart Home Assistant when it says to.

4. In Home Assistant, go to Configuration -> Integrations  -> Click "+ Add Integration"
5. Search for "Ecowitt Weather Station" and follow the instructions to setup.

Ecowitt should now appear as a card under the HA Integrations page with "Options" selection available at the bottom of the card.

**Comment by DaDre** [comment]
I have followed steps 1-4, however when I get to step 5, Ecowitt is not found. I've restarted HA and the Pi its running on several times. Any suggestions?

**Comment by garbled1** [comment]
In the logs does it show you are running a custom integration for ecowitt?

**Comment by DaDre** [comment]
Seeing the following in logs, so I'm assuming this means its installed:

`2020-12-22 11:46:08 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for ecowitt which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.`

and

`2020-12-22 11:46:39 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Getting repository information
2020-12-22 11:46:39 DEBUG (MainThread) [custom_components.hacs] <Integration garbled1/homeassistant_ecowitt> Getting repository information
2020-12-22 11:46:39 DEBUG (MainThread) [custom_components.hacs] <Integration garbled1/homeassistant_ecowitt> Running checks against 0.5
2020-12-22 11:46:39 DEBUG (MainThread) [custom_components.hacs] <Integration hacs/integration> Running checks against 1.9.0`

**Comment by DaDre** [comment]
Tried one more time just now and it showed up. Strange. But it's now working.
