### ISSUE TITLE
Cannot Install, now showing on HA Integrations

### ISSUE THREAD

**Issue by zejulio** [garbled1/homeassistant_ecowitt#33]
Hello, 

Just tried to install it and it does not show up on Home Assistant Integrations after reboot, so I cannot configure...
I am using the latest HA version on HassOS.

Thanks,

JS

**Comment by zejulio** [comment]
Solved!

I was installing over android app, i need to force close the app and open so it update the integrations list!

Working now thanks!

**Comment by garbled1** [comment]
Ahh.. never tried that, glad it's working for you now!
