### ISSUE TITLE
Missing sensors

### ISSUE THREAD

**Issue by kjelle392** [garbled1/homeassistant_ecowitt#4]
From the log:

Loggdetaljer (WARNING)
Logger: custom_components.ecowitt
Source: custom_components/ecowitt/__init__.py:272
Integration: Ecowitt Weather Station (documentation)
First occurred: 21:19:02 (4 occurrences)
Last logged: 21:19:02

Unhandled sensor type maxdailygust
Unhandled sensor type hourlyrainin
Unhandled sensor type totalrainin
Unhandled sensor type wh65batt

**Comment by garbled1** [comment]
Duplicate of #3 (though the 65 is unique).  Please follow that issue.  Thank you!
