### ISSUE TITLE
ecowitt logo in the integrations page

### ISSUE THREAD

**Issue by alexdelprete** [garbled1/homeassistant_ecowitt#46]
Minor cosmetic issue: in the integrations page the logo is missing:

![image](https://user-images.githubusercontent.com/7027842/110249283-c5b7f280-7f75-11eb-91d6-844cfeec022a.png)

Here's the link to ecowitt logo: https://osswww.ecowitt.net/shop/static/imgs/logo-dark.png

**Comment by garbled1** [comment]
HomeAssistant requires a high quality logo of specific size and shape..  At the time I could not find one that met the requirements, if you can find a really good one, then I (or you) could submit that...

https://github.com/home-assistant/brands/pull/1581

**Comment by alexdelprete** [comment]
I sent an email to Lucy, ecowitt's support coordinator, asking for a logo with those characteristics.

Will let you know the answer.

**Comment by alexdelprete** [comment]
They told me to use this one. I replied in the PR you linked, let's see what frenck says about it.

![apple-touch-icon](https://user-images.githubusercontent.com/7027842/110340181-44219c80-8029-11eb-9baf-6889de873405.png)

**Comment by alexdelprete** [comment]
They also sent me the logo "text version" they use on their website. They sent me the pdf, I converted it in png. They're both attached.

[logo.pdf](https://github.com/garbled1/homeassistant_ecowitt/files/6108471/logo.pdf)
![logo](https://user-images.githubusercontent.com/7027842/110470503-36c4ea80-80db-11eb-9bc7-0bc48fa6199c.png)

**Comment by garbled1** [comment]
OK, I'll wait a day or so and see if Frenk responds, if not, maybe I'll just open a new PR and try.  Thanks!

**Comment by garbled1** [comment]
do you have docs for that, or is there a protocol map somewhere?  I didn't know you could to be honest...  If you do, maybe open a new issue and we can discuss there..  I honestly had no idea they had a UDP protocol...  it's pull I assume?

**Comment by alexdelprete** [comment]
Yes, it's pull. There is a specific UDP port, 49000 iirc, so once you know the IP of the GW1000 you can use that to pull data from it. They have a doc they sent me for the UDP implementation with all data structure details, but it is not public, and they asked me to use it only for a specific dev project, and not share it publicly. But if you want to implement it, I can share it with you.

I'll open another issue to discuss this since you're interested...

**Comment by garbled1** [comment]
Regarding this.  Would you mind opening a new PR on brands to get these logos in?  Basically they have to be resized (in png) and a new PR made up.  I'm working on a PR now to put ecowitt in core, and if the logo is already in the custom_components brands repo, it's way way easier for me up front.

**Comment by alexdelprete** [comment]
Sorry for the delay, I missed the notification about your post.

![ecowitt icon](https://user-images.githubusercontent.com/7027842/145700880-2994ca07-0721-4ea9-ba84-57dea751f468.png)
![ecowitt logo](https://user-images.githubusercontent.com/7027842/145700882-73605c4e-bc14-487c-a46e-cc97037d8720.png)

This is the best I could come up with to respect the minimum requirements, hope the PR will be accepted. I'll submit it asap on your repo, so you can then utilize it for the official integration.

**Comment by alexdelprete** [comment]
PR submitted: https://github.com/home-assistant/brands/pull/2997

**Comment by alexdelprete** [comment]
Icon/Logo is ok now, I'll close this.
