### ISSUE TITLE
Integration doesn't load with core-2021.4.0

### ISSUE THREAD

**Issue by alexdelprete** [garbled1/homeassistant_ecowitt#52]
Just upgraded to 2021.4.0 and after the restart, the integration doesn't load anymore.

![image](https://user-images.githubusercontent.com/7027842/113946918-c27c8480-9809-11eb-9c93-44fbbc59c868.png)

![image](https://user-images.githubusercontent.com/7027842/113946935-c7d9cf00-9809-11eb-93aa-3bb802e00563.png)

**Comment by AdeZwart** [comment]
That's due to the required version number in the manifest. As a work around you can add the version number yourself in the manifest.json. This PR will solve the issue: #49

**Comment by SteGe88** [comment]
Same issue over here. Had to fix it with manually changing the version number. But there is already a PR from @AdeZwart available, so I think that should be the preffered way!

**Comment by alexdelprete** [comment]
> That's due to the required version number in the manifest. As a work around you can add the version number yourself in the manifest.json. This PR will solve the issue: #49

Nope. It's not the case, I had already tried it.

If I reinstall from scratch (HACS) and then I add the integration, I get this:

![image](https://user-images.githubusercontent.com/7027842/114058372-ae7d6500-9893-11eb-85f8-863855eb530f.png)

I'm not using 0.5 version when I install from HACS, I choose "master" because @garbled1 and I tested some customizations for the WH45 sensor. Later I'm gonna try the 0.5 branch and see what happens.

**Comment by alexdelprete** [comment]
Update: the upgrade to 2021.4 had issues with my db (I use MariaDB), so I had to reinstall it from scratch. I then proceeded to reinstall the ecowitt integration, and it worked straight away. So it was a specific issue, not a general one, it is working with HA 2021.4, so I'll close it now.

Thanks for the support.
