### ISSUE TITLE
Statistical sensor graph fix ?

### ISSUE THREAD

**Issue by mr-sneezy** [garbled1/homeassistant_ecowitt#72]
Hi guys, I'd like to add a statistical graph to Lovelace frontend of some Ecowitt sensorss, but I run into a problem doing that right now.
Anyone know a solution, seems to be about how the sensor state_class is defined ?
https://www.home-assistant.io/more-info/statistics/

**Comment by mr-sneezy** [comment]
I'll add a bit more info to this question in case it's not clear what I was talking about.
In short, has anyone else tried to add a Ecowitt sensor entity to a Statistical Graph Card ?

If I understand it's usage right (and yes there is a fair chance I don't), I can get hourly statistics of things like outdoor temperature and pressure graphed for up to 30 days straight, without much fuss. 

If I'm guessing right again, to have this work there needs to be a change to the state_class naming used in the Ecowitt integration source. 
If it works then graphing like this is available to us.
![image](https://user-images.githubusercontent.com/6261419/128852751-063bc03b-e8f7-481e-9ebc-99f56e579bfb.png)

**Comment by peetipablo** [comment]
Hey there, 

I was interested in setting this up as well, the statistics graphs are quite pretty.  It does say on the Statistics Graph Card page:

`Statistics are gathered every hour for sensors that support it.`

I'm assuming something needs to be changed with the sensors in order for them to be supported by the new statistics integration, but that's about as far as I have gotten.

**Comment by Armadill0** [comment]
I would say for most of the sensors the "state_class" attribute needs to be set to "measurement" as long as they contain current values.

For sensors which show a total amount and which are being reset from time to time there's a bit more to be done. More information can be found here: https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics

**Comment by garbled1** [comment]
Should be fixed now in 0.7
